### PR TITLE
Feature Implement Milestone: friendships-v2

### PR DESCRIPTION
**Pull request by Bluette1**
#### [Feature Implement Milestone: friendships-v2](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)
- Covers the following milestone
   - Social media website - Milestone: friendships v2
        - Friendships are implemented with two rows for each pair of friends
- Refactor the code for implementing the required friendship features
  - Make the necessary changes in the models
  - Make the necessary changes in the controllers
  - Fix breaking tests
- [Live demo](https://post-bk-app.herokuapp.com/)

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Bluette1 
### You have done well so far :clap: However, you have a few issues to fix before the project can be approved:-
- [x] Use recommended rubocop.yml, linters.yml and tests.yml files by Microverse, [refer from this link](https://github.com/microverseinc/linters-config/tree/master/ruby)
- [x] In the friendship model you can something like, see code below
```
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- [x] User model
```ruby
`# Users who needs to confirm friendship`
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
```ruby
# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
- [x] Getting posts by a user 
```ruby
def friends_and_own_posts
  Post.where(user: (self.friends + self))
end
```

### Make the changes and submit for another code review. Good luck.
- Happy hacking!

By Raymond
Slack @iamraymond

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for applying the suggested changes 
However, there are still changes to do

1. Here is what I have in the friendship table
```rb
2.6.5 :001 > Friendship.all
  Friendship Load (0.6ms)  SELECT  "friendships".* FROM "friendships" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friendship id: 1, friend_id: 2, inverse_friend_id: 1, created_at: "2020-09-09 22:20:27", updated_at: "2020-09-09 22:22:01", status: "confirmed">]> 
2.6.5 :002 > 
```
It's supposed to contain 2 rows but there is only one.

Kindly read the last reviews to know how to solve that, please

2. Kindly remove logic from views Ex: `_logged_in_user.html`. Kindly implment them into views helpers

3. Kindly read the last reviews, please.

Make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

**Comment by Bluette1** [comment]
@rOluochKe and @maelfosso, thank you very much for your review and feedback!

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved :heavy_check_mark:
### Well done Team, you did a good job :muscle:  by implementing the required changes :toolbox:
### This project is approved :white_check_mark:

### _Reviewed by Temitayo Adeleke._

**Comment by Bluette1** [comment]
@lekegitrepo, thank you very much for your review and feedback!

**Pull request merged**
